# Generated by Django 5.1.2 on 2024-10-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_image', models.ImageField(upload_to='uploads/images')),
            ],
        ),
    ]
